# Site settings
title: 			سیامک غلامعلی
description: 	طراح و توسعه‌دهنده رابط کاربری
baseurl: 		"/"
url: 				"http://siamakgholamali.ir"
name: 			سیامک غلامعلی
job: 				طراح و توسعه‌دهنده رابط کاربری
avatar: 			/images/siamak.jpg
email: 			siamak.gholamali@hotmail.com
github: 			https://github.com/siamakgholamali
twitter: 		https://twitter.com/siamakgholamali
facebook: 		https://www.facebook.com/siamak.gholamalii
instagram: 		https://instagram.com/siamakgholamali

# Build settings
markdown: 	kramdown
kramdown:
  input:    GFM
highlighter:   pygments
include: 		['.htaccess']
keep_files: 	['.git']
paginate: 		8
paginate_path: /page:num/
permalink:     /blog/:title
sass:
  sass_dir: _scss
  style:    :compressed
gems:
  - jekyll-sitemap
